version: '3'
services:
  web:
    build: .
    container_name: web
    command: bash -c "rm -f tmp/pids/server.pid && yarn install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  guard:
    build: .
    container_name: guard
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    command: bundle exec guard --no-bundler-warning --no-interactions